import Button from '../../../components/Button';
import Titulo from '@/app/components/Titulo';
import CaixaTexto from '../../../components/CaixaTexto'; // Importe o componente CaixaTexto
import styles from '../../../styles/Button.module.css'

export const metadata = {
  title: 'Acessar Sala',
  description: 'Generated by create next app',
}

export default function AcessarSala() {
  return (
    <>
      <Titulo text='ACESSAR SALA'></Titulo>

      {/* input Código da Sala */}
      <CaixaTexto text="Código da Sala" placeholder="Digite o código da sala" />

      {/* Input Apelido */}
      <CaixaTexto text="Apelido" placeholder="Digite seu apelido" />

      <Button className={styles.Button} text="Acessar Sala" href="pages/tela_grupo" id="tela_grupo" />
    </>
  );
}
