import Texto from '@/app/components/Texto'
import styles from '../../../styles/Texto.module.css'
import Button from "../../../components/Button"
import buttonStyle from '../../../styles/Button.module.css'
import stylesText from '../../../styles/CaixaDeTexto.module.css'
import CaixaDeTexto from '@/app/components/CaixaDeTexto'
import IconButton from '../../../components/IconButton'
import QrCode from '../../../components/QrCode'
import { FiHelpCircle } from "react-icons/fi";
import { IoCaretBack } from "react-icons/io5";

export const metadata = {
    title: 'Sala de Grupo',
    description: 'Generated by create next app',
  }

export default function GrupoHost(){
    return (
    <>
      <Texto className={styles.titulo} text='falácia'></Texto>
      <Button className={buttonStyle.voltarButton}  text="Voltar" href="criar_sala" id="voltar" />
      
      
>>>>>>> d09fdb970f2e10465a89b805007b52f9544ed7ed
    </>
    )
  }

