import styles from '../../styles/Titulo.module.css'
import Titulo from '@/app/components/Titulo'

export const metadata = {
    title: 'Créditos',
    description: 'Generated by create next app',
  }

  export default function Creditos(){
    return (
        <>
          <Titulo text='creditos'></Titulo>
        </>
          
           
      )


}