import styles from '../../../styles/Titulo.module.css'
import Titulo from '@/app/components/Titulo'
import TextoComum from '../../../components/TextoComum'

export const metadata = {
    title: 'Créditos',
    description: 'Generated by create next app',
  }

  export default function Creditos(){
    return (
      <>
        <Titulo text='creditos'></Titulo>
        <TextoComum>
          <p>
            Felipe Silva de Oliveira <br/>
            Gabriel Pinto Sasaki <br/>
            Matheus Pereira de Almeida <br/>
            Monique Pereira da Silva <br/>
            Veronica Cano Bernardino <br/>
            Vinicius Augusto Gomes Riso <br/>
          </p>
        </TextoComum>
      </>
          
           
      )


}