import Texto from '../../../components/Texto'
import styles from '../../../styles/Texto.module.css'

export const metadata = {
    title: 'Créditos',
    description: 'Generated by create next app',
  }

  export default function Creditos(){
    return (
      <>
        <Texto className={styles.tituloResponsivo} text='créditos'/>
        <Texto className={styles.textoComum} 
          text="Felipe Silva de Oliveira <br/>
          Gabriel Pinto Sasaki <br/>
          Matheus Pereira de Almeida <br/>
          Monique Pereira da Silva <br/>
          Veronica Cano Bernardino <br/>
          Vinicius Augusto Gomes Riso <br/>"/>
      </>
          
           
      )


}