export const metadata = {
    title: 'Criar Sala',
    description: 'Generated by create next app',
  }

import styles from '../../styles/Titulo.module.css'

  export default function CriarSala(){
    return (
        <>
          <header className={styles.titulo}>CRIAR SALA</header>
        </>
          
           
      )


}