import Button from "./components/Button";
import Texto from "./components/Texto";
import styles from './styles/Button.module.css'
import styles2 from './styles/Texto.module.css'

export const metadata = {
  title: 'FALÁCIA',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <Texto className={styles2.titulo} text='falácia'></Texto>
      <div>
        <nav>
          <Button className={styles.Button} text="Criar Sala" href="pages/criar_sala" id="criar_sala" />
        </nav>
        <nav>
          <Button className={styles.Button} text="Acessar Sala" href="pages/acessar_sala" id="acessar_sala" />
        </nav>
        <nav>
          <Button className={styles.Button} text="Como Jogar" href="pages/como_jogar" id="como_jogar" />
        </nav>
        <nav>
          <Button className={styles.Button} text="Créditos" href="pages/creditos" id="creditos" />
        </nav>
        {/* <nav>
          <Button className={styles.Button} text="Testes" href="pages/testes" id="testes" />
        </nav> */}
        
      </div>
    </>
  )
}
