import Titulo from "./components/Titulo"
import Button from "./components/Button";


export const metadata = {
  title: 'FALÁCIA',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <Titulo text='falácia'></Titulo>
      <div>
        <nav>
          <Button text="Criar Sala" href="pages/criar_sala" id="criar_sala" />
        </nav>
        <nav>
          <Button text="Acessar Sala" href="pages/acessar_sala" id="acessar_sala" />
        </nav>
        <nav>
          <Button text="Como Jogar" href="pages/como_jogar" id="como_jogar" />
        </nav>
        <nav>
          <Button text="Créditos" href="pages/creditos" id="creditos" />
        </nav>
        
      </div>
    </>
  )
}
