import Titulo from "./components/Titulo"
import styles2 from './styles/Button.module.css'
import Button from "./components/Button";


export const metadata = {
  title: 'FALÁCIA',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <header>
        <Titulo />
      </header>
      <div>
        <nav>
          <Button text="Criar Sala" href="pages/criar_sala" id="criar_sala" />
        </nav>
        <nav>
          <Button text="Acessar Sala" href="/acessar_sala" id="acessar_sala" />
        </nav>
        <nav>
          <Button text="Como Jogar" href="/como_jogar" id="como_jogar" />
        </nav>
        <nav>
          <Button text="Créditos" href="/creditos" id="creditos" />
        </nav>
        <nav>
          <Button text="PÁGINA TESTE" href="pages/dashboard" id="dashboard" />
        </nav>
      </div>
    </>
  )
}
