import Texto from '@/app/components/Texto'
import styles from '../../../styles/Texto.module.css'

export const metadata = {
    title: 'Sala de Grupo',
    description: 'Generated by create next app',
  }

  export default function SalaHost(){
    return (
      <>
        <Texto className={styles.titulo} text='Sala de Grupo'/>
        <Texto className={styles.textoComum} text='<p>Você é o HOST</p>'/>
           
      </>
          
           
      )


}