import Titulo from '@/app/components/Titulo'
import TextoComum from '../../../components/TextoComum'

export const metadata = {
    title: 'Sala de Grupo',
    description: 'Generated by create next app',
  }

  export default function SalaHost(){
    return (
      <>
        <Titulo text='Sala de Grupo'></Titulo>
        <TextoComum>
          <p>
            Você é o HOST
          </p>
        </TextoComum>
      </>
          
           
      )


}