import React from 'react';

import Texto from '@/app/components/Texto';
import CaixaTexto from '../../../components/InputTexto';
import Button from '../../../components/Button';
import styles from '../../../styles/Button.module.css'
import styles2 from '../../../styles/Texto.module.css'

export const metadata = {
  title: 'Criar Sala',
  description: 'Generated by create next app',
}

export default function CrirSala(){
   return (
   <>
     <Texto className={styles2.tituloResponsivo} text='Criar Sala' />
    
     <CaixaTexto text="Apelido:" placeholder="Digite seu apelido"/>
     <Button className={styles.Button} text="Criar Sala" href="host" id="host" />
   </>
   )
 }



