import styles from '../../styles/Titulo.module.css'

export const metadata = {
    title: 'Acessar Sala',
    description: 'Generated by create next app',
  }

  export default function AcessarSala(){
    return (
        <>
          <header className={styles.titulo}>ACESSAR SALA</header>
        </>
          
           
      )


}