import styles from '../../styles/Titulo.module.css'
import Button from '../../components/Button'
import Titulo from '@/app/components/Titulo'


export const metadata = {
    title: 'Acessar Sala',
    description: 'Generated by create next app',
  }

  export default function AcessarSala(){
    return (
        <>
            <Titulo text='ACESSAR SALA'></Titulo>
           
               

        </>
   
      )


}