import styles from '../../styles/Titulo.module.css'

export const metadata = {
    title: 'Créditos',
    description: 'Generated by create next app',
  }

  export default function Creditos(){
    return (
        <>
          <header className={styles.titulo}>CRÉDITOS</header>
        </>
          
           
      )


}