import styles from '../../styles/Titulo.module.css'
import Titulo from '@/app/components/Titulo'

export const metadata = {
    title: 'Como Jogar',
    description: 'Generated by create next app',
  }

  export default function ComoJogar(){
    return (
        <>
         <Titulo text='como jogar'></Titulo>
        </>
          
           
      )


}