import Texto from '@/app/components/Texto'
import styles from '../../../styles/Texto.module.css'

export const metadata = {
    title: 'Como Jogar',
    description: 'Generated by create next app',
  }
  
  export default function ComoJogar(){
    return (
        <>
        <Texto className={styles.tituloResponsivo} text='como jogar'/>
        
        </>
          
           
      )
}