import styles from '../../styles/Titulo.module.css'

export const metadata = {
    title: 'Como Jogar',
    description: 'Generated by create next app',
  }

  export default function ComoJogar(){
    return (
        <>
          <header className={styles.titulo}>COMO JOGAR</header>
        </>
          
           
      )


}